### ISSUE TITLE
DOCUMENTATION: Translate `0.0 The Theory.md`

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/The-Standard-Uzbek#10]

**Comment by ElbekDeveloper** [comment]
0 The Theory.md Sahifasini #10 - issue sini
men va Ahmadjon tarjima qilayapmiz . 

Sherik bo'lmoqchi bo'lsangiz :

telegram - @xakimov1610 ,  @Ahmadjohnuz  
discord -  Nosirbek#5376 ,

**Comment by XakimovNosirbek** [comment]
Bu sahifani men va Ahmadjon tarjima qilayapmiz . 

Sherik bo'lmoqchi bo'lsangiz - [`telegram`-men](https://t.me/xakimov1610) , [`telegram`-Ahmadjon](https://t.me/Ahmadjohnuz) /  `discord` da  **Nosirbek#5376**
