### ISSUE TITLE
DOCUMENTATION: Translate `0.1 Purposing, Modeling & Simulation.md`

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/The-Standard-Uzbek#11]

**Comment by theyasub** [comment]
Assalomu alaykum Elbek aka yaxshimisiz men ham yordam bermoqchiman @ElbekDeveloper siz qaysidir mavzuni aytsangiz men shunga kirishaman.

**Comment by ElbekDeveloper** [comment]
> Assalomu alaykum Elbek aka yaxshimisiz men ham yordam bermoqchiman @ElbekDeveloper siz qaysidir mavzuni aytsangiz men shunga kirishaman.

Shu mavzuni olaverishingiz mumkin.

**Comment by Ozodbek00** [comment]
@Rashidovicc Bilan birga qilamiz

**Comment by theyasub** [comment]
@Ozodbek00 ok
