### ISSUE TITLE
DOCUMENTATION: Translate Brokers

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/The-Standard-Uzbek#37]

**Comment by Temurkhann** [comment]
Hello, I also wanted to translate as a contributor

**Comment by mirzohidsobirjonov** [comment]
@ElbekDeveloper Assalomu alaykum, Elbek aka menham kitob tarjimasiga o`z hissamni qo`shmoqchi edim. Shunga birorta mavzu bera olasizmi?

**Comment by ElbekDeveloper** [comment]
Telegramda @ElbekDeveloper ga yozing. 
@mirzohidsobirjonov

**Comment by iamDiyorjon** [comment]
I will do this.

**Comment by ElbekDeveloper** [comment]
@iamDiyorjon qo'shib qoydim rahmat ; )
