### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by shahbozkhurramov** [hassanhabib/The-Standard-Uzbek#55]
Hi I just saw your translation. For people who are translating, All keywords should not be translated into uzbek. Thats not good. We dont write service or namespace names in uzbek for example. I recommend to remain all keywords, method names etc. in english. Otherwise it can be absurd for a reader.

**Comment by ElbekDeveloper** [comment]
Thanks for the feedback, brother. I appreciate it <3
